stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy_develop
  - deploy_main

variables:
  GIT_STRATEGY: clone
  GRADLE_OPTS: "-Dorg:gradle.daemon=false"

build:
  stage: build
  tags: 
    - dalfcs_docker_kvm
  image: gradle:latest
  script: 
    - ./gradlew assemble --scan

test:
  stage: test
  tags:
    - dalfcs_docker_kvm
  image: gradle:latest
  script: 
    - ./gradlew check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/binary/TEST-*.xml

deploy-test:
  type: deploy
  stage: deploy_develop
  tags:
    - dalfcs_docker_kvm
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_DEV_APPLICATION_NAME --api-key=$HEROKU_API_KEY
  only:
    - Develop
    
deploy-main:
  type: deploy
  stage: deploy_main
  tags:
    - dalfcs_docker_kvm
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APPLICATION_NAME --api-key=$HEROKU_API_KEY
  only:
    - main