stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  GIT_STRATEGY: clone
  GRADLE_OPTS: "-Dorg:gradle.daemon=false"
  
 before_script:
    - apk add --no-cache openssh-client
    - chmod 777 ./gradlew

build:
  stage: build
  tags: 
    - dalfcs_docker_kvm
  image: gradle:latest
  script: 
    - ./gradlew assemble --scan

test:
  stage: test
  tags:
    - dalfcs_docker_kvm
  image: gradle:latest
  script: 
    - ./gradlew check

deploy-test:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APPLICATION_NAME --api-key=$HEROKU_API_KEY